//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleWebserviceClient.Registry {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistributableObject", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SampleWebserviceClient.Registry.ComponentInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SampleWebserviceClient.Registry.GameInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SampleWebserviceClient.Registry.EndPoint))]
    public partial class DistributableObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComponentInfo", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SampleWebserviceClient.Registry.GameInfo))]
    public partial class ComponentInfo : SampleWebserviceClient.Registry.DistributableObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SampleWebserviceClient.Registry.EndPoint CommmunicationEndPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SampleWebserviceClient.Registry.EndPoint CommmunicationEndPoint {
            get {
                return this.CommmunicationEndPointField;
            }
            set {
                if ((object.ReferenceEquals(this.CommmunicationEndPointField, value) != true)) {
                    this.CommmunicationEndPointField = value;
                    this.RaisePropertyChanged("CommmunicationEndPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameInfo", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    public partial class GameInfo : SampleWebserviceClient.Registry.ComponentInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AliveTimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SampleWebserviceClient.Registry.GameInfo.GameStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AliveTimestamp {
            get {
                return this.AliveTimestampField;
            }
            set {
                if ((this.AliveTimestampField.Equals(value) != true)) {
                    this.AliveTimestampField = value;
                    this.RaisePropertyChanged("AliveTimestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SampleWebserviceClient.Registry.GameInfo.GameStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="GameInfo.GameStatus", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        public enum GameStatus : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NOT_INITIAlIZED = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            AVAILABLE = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RUNNING = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            COMPLETED = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            DEAD = 4,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EndPoint", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    public partial class EndPoint : SampleWebserviceClient.Registry.DistributableObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PortField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Address {
            get {
                return this.AddressField;
            }
            set {
                if ((this.AddressField.Equals(value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Registry.IRegistrar")]
    public interface IRegistrar {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrar/RegisterGame", ReplyAction="http://tempuri.org/IRegistrar/RegisterGameResponse")]
        SampleWebserviceClient.Registry.GameInfo RegisterGame(string label, SampleWebserviceClient.Registry.EndPoint publicEP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrar/RegisterGame", ReplyAction="http://tempuri.org/IRegistrar/RegisterGameResponse")]
        System.Threading.Tasks.Task<SampleWebserviceClient.Registry.GameInfo> RegisterGameAsync(string label, SampleWebserviceClient.Registry.EndPoint publicEP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrar/GetGames", ReplyAction="http://tempuri.org/IRegistrar/GetGamesResponse")]
        SampleWebserviceClient.Registry.GameInfo[] GetGames(SampleWebserviceClient.Registry.GameInfo.GameStatus status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrar/GetGames", ReplyAction="http://tempuri.org/IRegistrar/GetGamesResponse")]
        System.Threading.Tasks.Task<SampleWebserviceClient.Registry.GameInfo[]> GetGamesAsync(SampleWebserviceClient.Registry.GameInfo.GameStatus status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrar/AmAlive", ReplyAction="http://tempuri.org/IRegistrar/AmAliveResponse")]
        void AmAlive(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrar/AmAlive", ReplyAction="http://tempuri.org/IRegistrar/AmAliveResponse")]
        System.Threading.Tasks.Task AmAliveAsync(int gameId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrar/ChangeStatus", ReplyAction="http://tempuri.org/IRegistrar/ChangeStatusResponse")]
        void ChangeStatus(int gameId, SampleWebserviceClient.Registry.GameInfo.GameStatus status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistrar/ChangeStatus", ReplyAction="http://tempuri.org/IRegistrar/ChangeStatusResponse")]
        System.Threading.Tasks.Task ChangeStatusAsync(int gameId, SampleWebserviceClient.Registry.GameInfo.GameStatus status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistrarChannel : SampleWebserviceClient.Registry.IRegistrar, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistrarClient : System.ServiceModel.ClientBase<SampleWebserviceClient.Registry.IRegistrar>, SampleWebserviceClient.Registry.IRegistrar {
        
        public RegistrarClient() {
        }
        
        public RegistrarClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistrarClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrarClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistrarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SampleWebserviceClient.Registry.GameInfo RegisterGame(string label, SampleWebserviceClient.Registry.EndPoint publicEP) {
            return base.Channel.RegisterGame(label, publicEP);
        }
        
        public System.Threading.Tasks.Task<SampleWebserviceClient.Registry.GameInfo> RegisterGameAsync(string label, SampleWebserviceClient.Registry.EndPoint publicEP) {
            return base.Channel.RegisterGameAsync(label, publicEP);
        }
        
        public SampleWebserviceClient.Registry.GameInfo[] GetGames(SampleWebserviceClient.Registry.GameInfo.GameStatus status) {
            return base.Channel.GetGames(status);
        }
        
        public System.Threading.Tasks.Task<SampleWebserviceClient.Registry.GameInfo[]> GetGamesAsync(SampleWebserviceClient.Registry.GameInfo.GameStatus status) {
            return base.Channel.GetGamesAsync(status);
        }
        
        public void AmAlive(int gameId) {
            base.Channel.AmAlive(gameId);
        }
        
        public System.Threading.Tasks.Task AmAliveAsync(int gameId) {
            return base.Channel.AmAliveAsync(gameId);
        }
        
        public void ChangeStatus(int gameId, SampleWebserviceClient.Registry.GameInfo.GameStatus status) {
            base.Channel.ChangeStatus(gameId, status);
        }
        
        public System.Threading.Tasks.Task ChangeStatusAsync(int gameId, SampleWebserviceClient.Registry.GameInfo.GameStatus status) {
            return base.Channel.ChangeStatusAsync(gameId, status);
        }
    }
}
